# 海澜之家 V1.0
## 91Panda 制作 2025-2-4
## 适用于青楼之王0.3版本



init 900 python:


    config.label_overrides["init_items"] = "Panda_init_items"

    HLAGROUP_template = Mod(
        
                ## Basic mod information (Important: Version is used to check for new versions of the mod. Failure to update the version number may lead to broken mods and saved games)
                name = "海澜之家",
                folder = "HLA GROUP",
                creator = "PANDA",
                version = 1.0,
                pic = "海澜之家封面.png",
                description = """神秘的服装商来到了泽恩拓展业务。他带来了质量更好，价格也更贵的各类新品衣物。\n海澜之家，每年逛2次，每次都有新发现！""",

                ## Event dictionary (all mod events must be declared here)
                )
    # 添加新的 Item  

label Panda_init_items():
    # Each item exists only once as an Item object. Copies used in-game are instances of the ItemInstance object.

    python:


        # REGULAR ITEMS #

        all_items = [
                    Item(name = _('Short sword'), target = 'MC', type = IT_Weapon, pic = 'Short sword.webp', rank = 1, rarity = 1, price = 250, effects = (Effect('change', 'strength', 1), ), description =__(  "")),
                    Item(name = _('Cutlass'), target = 'MC', type = IT_Weapon, pic = 'Cutlass.webp', rank = 1, rarity = 2, price = 500, effects = (Effect('change', 'strength', 2), ), description =__(  "It's not a knife. That's a knife.")),
                    Item(name = _('Axe'), target = 'MC', type = IT_Weapon, pic = 'Axe.webp', rank = 2, rarity = 2, price = 1000, effects = (Effect('change', 'strength', 2), Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Lance'), target = 'MC', type = IT_Weapon, pic = 'Lance.webp', rank = 2, rarity = 2, price = 2500, effects = (Effect('change', 'strength', 3), Effect('change', 'charisma', 1), ), description =__(  "")),
                    Item(name = _('Long sword'), target = 'MC', type = IT_Weapon, pic = 'Long sword.webp', rank = 2, rarity = 3, price = 3500, effects = (Effect('change', 'strength', 3), Effect('change', 'charisma', 1), Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Rapier'), target = 'MC', type = IT_Weapon, pic = 'Rapier.webp', rank = 3, rarity = 3, price = 5000, effects = (Effect('change', 'strength', 4), Effect('change', 'charisma', 2), ), description =__(  "")),
                    Item(name = _('Battle axe'), target = 'MC', type = IT_Weapon, pic = 'Battle axe.webp', rank = 3, rarity = 3, price = 10000, effects = (Effect('change', 'strength', 5), Effect('change', 'spirit', 2), ), description =__(  "")),
                    Item(name = _('Warhammer'), target = 'MC', type = IT_Weapon, pic = 'Warhammer.webp', rank = 3, rarity = 4, price = 17500, effects = (Effect('change', 'strength', 5), Effect('change', 'charisma', 2), Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Holy sword'), target = 'MC', type = IT_Weapon, pic = 'Holy sword.webp', rank = 4, rarity = "U", price = 40000, effects = (Effect('change', 'strength', 6), Effect('change', 'spirit', 3), ), description =__(  "This sword hums with power. The light reflects so brightly on its blade it could blind the angels themselves.")),
                    Item(name = _('Demon sword'), target = 'MC', type = IT_Weapon, pic = 'Demon sword.webp', rank = 4, rarity = "S", price = 100000, effects = (Effect('change', 'strength', 8), Effect('change', 'charisma', 4), Effect('change', 'spirit', -2), ), description =__(  "The blade pulses with the dark fury of the demon trapped inside. They say he devours every poor soul that gets slain by this blade.")),
                    Item(name = _('Broom staff'), target = 'MC', type = IT_Weapon, pic = 'Broom staff.webp', rank = 1, rarity = 1, price = 250, effects = (Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Wooden staff'), target = 'MC', type = IT_Weapon, pic = 'Wooden staff.webp', rank = 1, rarity = 2, price = 500, effects = (Effect('change', 'spirit', 2), ), description =__(  "")),
                    Item(name = _('Goblin staff'), target = 'MC', type = IT_Weapon, pic = 'Goblin staff.webp', rank = 2, rarity = 2, price = 1000, effects = (Effect('change', 'charisma', 1), Effect('change', 'spirit', 2), ), description =__(  "")),
                    Item(name = _('Bronze staff'), target = 'MC', type = IT_Weapon, pic = 'Bronze staff.webp', rank = 2, rarity = 2, price = 2500, effects = (Effect('change', 'strength', 1), Effect('change', 'spirit', 3), ), description =__(  "")),
                    Item(name = _('Wind staff'), target = 'MC', type = IT_Weapon, pic = 'Wind staff.webp', rank = 2, rarity = 3, price = 3500, effects = (Effect('change', 'strength', 1), Effect('change', 'charisma', 1), Effect('change', 'spirit', 3), ), description =__(  "")),
                    Item(name = _('Healing staff'), target = 'MC', type = IT_Weapon, pic = 'Healing staff.webp', rank = 3, rarity = 3, price = 5000, effects = (Effect('change', 'charisma', 2), Effect('change', 'spirit', 4), ), description =__(  "")),
                    Item(name = _('Thunder staff'), target = 'MC', type = IT_Weapon, pic = 'Thunder staff.webp', rank = 3, rarity = 3, price = 10000, effects = (Effect('change', 'strength', 2), Effect('change', 'spirit', 5), ), description =__(  "")),
                    Item(name = _('Emerald staff'), target = 'MC', type = IT_Weapon, pic = 'Emerald staff.webp', rank = 3, rarity = 4, price = 17500, effects = (Effect('change', 'strength', 1), Effect('change', 'charisma', 2), Effect('change', 'spirit', 5), ), description =__(  "")),
                    Item(name = _('Crystal staff'), target = 'MC', type = IT_Weapon, pic = 'Crystal staff.webp', rank = 4, rarity = 4, price = 40000, effects = (Effect('change', 'strength', 3), Effect('change', 'spirit', 6), ), description =__(  "")),
                    Item(name = _('Angel staff'), target = 'MC', type = IT_Weapon, pic = 'Angel staff.webp', rank = 4, rarity = 5, price = 100000, effects = (Effect('change', 'charisma', 2), Effect('change', 'spirit', 8), ), description =__(  "")),
                    Item(name = _('Throwing knife'), target = 'MC', type = IT_Weapon, pic = 'Throwing knife.webp', rank = 1, rarity = 1, price = 250, effects = (Effect('change', 'charisma', 1), ), description =__(  "")),
                    Item(name = _('Throwing axe'), target = 'MC', type = IT_Weapon, pic = 'Throwing axe.webp', rank = 1, rarity = 2, price = 500, effects = (Effect('change', 'charisma', 2), ), description =__(  "")),
                    Item(name = _('Bow'), target = 'MC', type = IT_Weapon, pic = 'Bow.webp', rank = 2, rarity = 2, price = 1000, effects = (Effect('change', 'strength', 1), Effect('change', 'charisma', 2), ), description =__(  "")),
                    Item(name = _('Ornate bow'), target = 'MC', type = IT_Weapon, pic = 'Ornate bow.webp', rank = 2, rarity = 2, price = 2500, effects = (Effect('change', 'charisma', 3), Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Flintlock'), target = 'MC', type = IT_Weapon, pic = 'Flintlock.webp', rank = 2, rarity = 3, price = 3500, effects = (Effect('change', 'strength', 2), Effect('change', 'charisma', 3), ), description =__(  "")),
                    Item(name = _('Crossbow'), target = 'MC', type = IT_Weapon, pic = 'Crossbow.webp', rank = 3, rarity = 3, price = 5000, effects = (Effect('change', 'strength', 1), Effect('change', 'charisma', 4), Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Repeater'), target = 'MC', type = IT_Weapon, pic = 'Repeater.webp', rank = 3, rarity = 3, price = 10000, effects = (Effect('change', 'strength', 2), Effect('change', 'charisma', 5), ), description =__(  "")),
                    Item(name = _('Blunderbuss'), target = 'MC', type = IT_Weapon, pic = 'Blunderbuss.webp', rank = 3, rarity = 4, price = 17500, effects = (Effect('change', 'strength', 3), Effect('change', 'charisma', 5), ), description =__("This. Is. My boomstick!")),
                    Item(name = _('Holy handgrenade'), target = 'MC', type = IT_Weapon, pic = 'Holy handgrenade.webp', rank = 4, rarity = 4, price = 40000, effects = (Effect('change', 'charisma', 6), Effect('change', 'spirit', 3), ), description =__(  "")),
                    Item(name = _('Death dispenser'), target = 'MC', type = IT_Weapon, pic = 'Death dispenser.webp', rank = 4, rarity = 5, price = 100000, effects = (Effect('change', 'strength', 4), Effect('change', 'charisma', 8), Effect('change', 'spirit', -2), ), description =__(  "")),
                    Item(name = _('Arios amulet'), target = 'MC', type = IT_Necklace, pic = 'Arios amulet.webp', rank = 1, rarity = "U", price = 25000, effects = (), description =__("Unique reward for completing the Arios knight quest.")),
                    Item(name = _('Shalia talisman'), target = 'MC', type = IT_Necklace, pic = 'Shalia talisman.webp', rank = 1, rarity = "U", price = 25000, effects = (), description =__("Unique reward for completing the Shalia shadow quest.")),
                    Item(name = _('Merchant sigil'), target = 'MC', type = IT_Necklace, pic = 'Merchant sigil.webp', rank = 1, rarity = "U", price = 25000, effects = (), description =__("Unique reward for completing the guild of merchants quest.")),
                    Item(name = _('Fur boots'), target = 'MC', type = IT_Accessory, pic = 'Fur boots.webp', rank = 1, rarity = 1, price = 500, effects = (Effect('change', 'speed', 1), ), ),
                    Item(name = _('Leather boots'), target = 'MC', type = IT_Accessory, pic = 'Leather boots.webp', rank = 1, rarity = 2, price = 2000, effects = (Effect('change', 'speed', 2), ), ),
                    Item(name = _('Elven boots'), target = 'MC', type = IT_Accessory, pic = 'Elven boots.webp', rank = 2, rarity = 3, price = 10000, effects = (Effect('change', 'speed', 3), ), ),
                    Item(name = _('Horse'), target = 'MC', type = IT_Accessory, pic = 'Horse.webp', rank = 3, rarity = 4, price = 50000, effects = (Effect('change', 'speed', 4), ), ),
                    Item(name = _('Dark horse'), target = 'MC', type = IT_Accessory, pic = 'Dark horse.webp', rank = 4, rarity = 5, price = 150000, effects = (Effect('change', 'speed', 5), ), ),
                    Item(name = _('Dragon egg'), target = 'MC', type = IT_Misc, pic = 'Dragon egg.webp', rank = 1, rarity = "S", charges = 1, price = 5000, effects = (Effect('gain', 'skill points', 1), ), description =__(  "'He was no dragon...'\nEat this at your own risk!"), sound = "crunch.ogg", hidden_effect = True),
                    Item(name = _('Knuckle duster'), target = 'girl', type = IT_Weapon, pic = 'Knuckle duster.webp', rank = 1, rarity = 1, price = 50, effects = (Effect('change', 'defense', 1), ), ),
                    Item(name = _('Hook'), target = 'girl', type = IT_Weapon, pic = 'Hook.webp', rank = 1, rarity = 1, price = 250, effects = (Effect('change', 'defense', 2), ), ),
                    Item(name = _('Shiv'), target = 'girl', type = IT_Weapon, pic = 'Shiv.webp', rank = 1, rarity = 2, price = 500, effects = (Effect('change', 'defense', 3), ), ),
                    Item(name = _('Knife'), target = 'girl', type = IT_Weapon, pic = 'Knife.webp', rank = 2, rarity = 2, price = 1000, effects = (Effect('change', 'defense', 4), ), ),
                    Item(name = _('Dagger'), target = 'girl', type = IT_Weapon, pic = 'Dagger.webp', rank = 2, rarity = 2, price = 1750, effects = (Effect('change', 'defense', 5), ), ),
                    Item(name = _('Sacrificial knife'), target = 'girl', type = IT_Weapon, pic = 'Sacrificial knife.webp', rank = 2, rarity = 3, price = 2750, effects = (Effect('change', 'defense', 6), ), ),
                    Item(name = _('Mace'), target = 'girl', type = IT_Weapon, pic = 'Mace.webp', rank = 3, rarity = 3, price = 5000, effects = (Effect('change', 'defense', 7), ), ),
                    Item(name = _('Whip'), target = 'girl', type = IT_Weapon, pic = 'Whip.webp', rank = 3, rarity = 4, price = 10000, effects = (Effect('change', 'defense', 8), ), ),
                    Item(name = _('Steel whip'), target = 'girl', type = IT_Weapon, pic = 'Steel whip.webp', rank = 4, rarity = 4, price = 25000, effects = (Effect('change', 'defense', 9), ), ),
                    Item(name = _('Magic blade'), target = 'girl', type = IT_Weapon, pic = 'Magic blade.webp', rank = 4, rarity = 5, price = 60000, effects = (Effect('change', 'defense', 10), ), ),
                    Item(name = _('Dildo'), target = 'girl', type = IT_Toy, pic = 'Dildo.webp', rank = 1, rarity = 2, charges = 8, price = 125, effects = (Effect('gain', 'sex', 1, 0.5), ), description =__("Chance to improve Sex when resting (limited uses).")),
                    Item(name = _('XL dildo'), target = 'girl', type = IT_Toy, pic = 'XL dildo.webp', rank = 2, rarity = 3, charges = 8, price = 500, effects = (Effect('gain', 'sex', 2, 0.5), ), description =__("Chance to improve Sex when resting (limited uses).")),
                    Item(name = _('XXL dildo'), target = 'girl', type = IT_Toy, pic = 'XXL dildo.webp', rank = 3, rarity = 4, charges = 8, price = 2500, effects = (Effect('gain', 'sex', 3, 0.5), ), description =__("Chance to improve Sex when resting (limited uses).")),
                    Item(name = _('Black dildo'), target = 'girl', type = IT_Toy, pic = 'Black dildo.webp', rank = 4, rarity = 5, charges = 8, price = 10000, effects = (Effect('gain', 'sex', 5, 0.5), ), description =__("Chance to improve Sex when resting (limited uses).")),
                    Item(name = _('Butt plug'), target = 'girl', type = IT_Toy, pic = 'Butt plug.webp', rank = 1, rarity = 2, charges = 8, price = 125, effects = (Effect('gain', 'anal', 1, 0.5), ), description =__("Chance to improve Anal when resting (limited uses).")),
                    Item(name = _('Butt pump'), target = 'girl', type = IT_Toy, pic = 'Butt pump.webp', rank = 2, rarity = 3, charges = 8, price = 500, effects = (Effect('gain', 'anal', 2, 0.5), ), description =__("Chance to improve Anal when resting (limited uses).")),
                    Item(name = _('Anal dildo'), target = 'girl', type = IT_Toy, pic = 'Anal dildo.webp', rank = 3, rarity = 4, charges = 8, price = 2500, effects = (Effect('gain', 'anal', 3, 0.5), ), description =__("Chance to improve Anal when resting (limited uses).")),
                    Item(name = _('Anal beads'), target = 'girl', type = IT_Toy, pic = 'Anal beads.webp', rank = 4, rarity = 5, charges = 8, price = 10000, effects = (Effect('gain', 'anal', 5, 0.5), ), description =__("Chance to improve Anal when resting (limited uses).")),
                    Item(name = _('Ropes'), target = 'girl', type = IT_Toy, pic = 'Ropes.webp', rank = 1, rarity = 2, charges = 8, price = 125, effects = (Effect('gain', 'fetish', 1, 0.5), ), description =__("Chance to improve Fetish when resting (limited uses).")),
                    Item(name = _('Cuffs'), target = 'girl', type = IT_Toy, pic = 'Cuffs.webp', rank = 2, rarity = 3, charges = 8, price = 500, effects = (Effect('gain', 'fetish', 2, 0.5), ), description =__("Chance to improve Fetish when resting (limited uses).")),
                    Item(name = _('Gag'), target = 'girl', type = IT_Toy, pic = 'Gag.webp', rank = 3, rarity = 4, charges = 8, price = 2500, effects = (Effect('gain', 'fetish', 3, 0.5), ), description =__("Chance to improve Fetish when resting (limited uses).")),
                    Item(name = _('Blindfold'), target = 'girl', type = IT_Toy, pic = 'Blindfold.webp', rank = 4, rarity = 5, charges = 8, price = 10000, effects = (Effect('gain', 'fetish', 5, 0.5), ), description =__("Chance to improve Fetish when resting (limited uses).")),
                    Item(name = _('Arousing gel'), target = 'girl', type = IT_Toy, pic = 'Arousing gel.webp', rank = 1, rarity = 2, charges = 8, price = 125, effects = (Effect('gain', 'service', 1, 0.5), ), description =__("Chance to improve Service when resting (limited uses).")),
                    Item(name = _('Egg vibrator'), target = 'girl', type = IT_Toy, pic = 'Egg vibrator.webp', rank = 2, rarity = 3, charges = 8, price = 500, effects = (Effect('gain', 'service', 2, 0.5), ), description =__("Chance to improve Service when resting (limited uses).")),
                    Item(name = _('Long vibrator'), target = 'girl', type = IT_Toy, pic = 'Long vibrator.webp', rank = 3, rarity = 4, charges = 8, price = 2500, effects = (Effect('gain', 'service', 3, 0.5), ), description =__("Chance to improve Service when resting (limited uses).")),
                    Item(name = _('Arcanic vibrator'), target = 'girl', type = IT_Toy, pic = 'Arcanic vibrator.webp', rank = 4, rarity = 5, charges = 8, price = 10000, effects = (Effect('gain', 'service', 5, 0.5), ), description =__("Chance to improve Service when resting (limited uses).")),
                    Item(name = _('Lucky charm'), target = 'girl', type = IT_Necklace, pic = 'Lucky charm.webp', rank = 1, rarity = 2, price = 1250, effects = (Effect('special', 'lucky', 1), ), description =__("It is said to bring luck to its owner. The rabbit it belonged to might disagree...")),
                    Item(name = _('Leather choker'), target = 'girl', type = IT_Necklace, pic = 'Leather choker.webp', rank = 1, rarity = 2, price = 750, effects = (Effect('boost', 'obedience tests', 0.2), ), ),
                    Item(name = _('Bronze amulet'), target = 'girl', type = IT_Necklace, pic = 'Bronze amulet.webp', rank = 2, rarity = 3, price = 2500, effects = (Effect('boost', 'all regular skills gains', 0.05), ), ),
                    Item(name = _('Silver amulet'), target = 'girl', type = IT_Necklace, pic = 'Silver amulet.webp', rank = 3, rarity = 4, price = 12500, effects = (Effect('boost', 'all regular skills gains', 0.1), ), ),
                    Item(name = _('Gold amulet'), target = 'girl', type = IT_Necklace, pic = 'Gold amulet.webp', rank = 4, rarity = 5, price = 25000, effects = (Effect('boost', 'all regular skills gains', 0.15), ), ),
                    Item(name = _('Monster pearl necklace'), target = 'girl', type = IT_Necklace, pic = 'Monster pearl necklace.webp', rank = 3, rarity = 5, price = 25000, effects = (Effect('boost', 'all sex skills gains', 0.1), ), description =__(  "It came from the sea...")),
                    Item(name = _('Ale'), target = 'girl', type = IT_Supplies, pic = 'Ale.webp', rank = 1, rarity = 1, charges = 10, price = 500, effects = (Effect('change', 'waitress results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Massage oil'), target = 'girl', type = IT_Supplies, pic = 'Massage oil.webp', rank = 1, rarity = 1, charges = 10, price = 500, effects = (Effect('change', 'masseuse results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Tanning oil'), target = 'girl', type = IT_Supplies, pic = 'Tanning oil.webp', rank = 1, rarity = 1, charges = 10, price = 500, effects = (Effect('change', 'dancer results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Fans'), target = 'girl', type = IT_Supplies, pic = 'Fans.webp', rank = 1, rarity = 1, charges = 10, price = 500, effects = (Effect('change', 'geisha results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Sensual perfume'), target = 'girl', type = IT_Supplies, pic = 'Sensual perfume.webp', rank = 1, rarity = 3, charges = 10, price = 750, effects = (Effect('change', 'service results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Gel'), target = 'girl', type = IT_Supplies, pic = 'Gel.webp', rank = 1, rarity = 3, charges = 10, price = 750, effects = (Effect('change', 'sex results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Enema'), target = 'girl', type = IT_Supplies, pic = 'Enema.webp', rank = 1, rarity = 3, charges = 10, price = 750, effects = (Effect('change', 'anal results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Wax'), target = 'girl', type = IT_Supplies, pic = 'Wax.webp', rank = 1, rarity = 3, charges = 10, price = 750, effects = (Effect('change', 'fetish results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Glasses'), target = 'girl', type = IT_Accessory, pic = 'Glasses.webp', rank = 1, rarity = 3, price = 1000, effects = (Effect('boost', 'xp gains', 0.1), ), ),
                    Item(name = _('Tail'), target = 'girl', type = IT_Accessory, pic = 'Tail.webp', rank = 1, rarity = 3, price = 1000, effects = (Effect('boost', 'reputation gains', 0.2), ), ),
                    Item(name = _('Bunny ears'), target = 'girl', type = IT_Accessory, pic = 'Bunny ears.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'waitress results', 1), ), ),
                    Item(name = _('Hairpin'), target = 'girl', type = IT_Accessory, pic = 'Hairpin.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'masseuse results', 1), ), ),
                    Item(name = _('Nun veil'), target = 'girl', type = IT_Accessory, pic = 'Nun veil.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'dancer results', 1), ), ),
                    Item(name = _('Noh mask'), target = 'girl', type = IT_Accessory, pic = 'Noh mask.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'geisha results', 1), ), ),
                    Item(name = _('Cat ears'), target = 'girl', type = IT_Accessory, pic = 'Cat ears.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'service results', 1), ), ),
                    Item(name = _('Nurse hat'), target = 'girl', type = IT_Accessory, pic = 'Nurse hat.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'sex results', 1), ), ),
                    Item(name = _('Leather cap'), target = 'girl', type = IT_Accessory, pic = 'Leather cap.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'anal results', 1), ), ),
                    Item(name = _('Maid hat'), target = 'girl', type = IT_Accessory, pic = 'Maid hat.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'fetish results', 1), ), ),
                    Item(name = _('Magic notebook'), target = 'MC', type = IT_Passive, pic = 'Magic notebook.webp', template = False, rank = 1, rarity = "S", price = 0, effects = (Effect('special', 'notebook', 1), ), description =__("This handy notebook will store all the information you know about your girls. It magically records all your thoughts. Wait, don't think about {i}that{/i}... Too late."), hidden_effect = True),
                    Item(name = _('Healing powder'), target = 'minion', type = IT_Misc, pic = 'healing powder.webp', template = False, rank = 1, rarity = "M", charges = 1, price = 100, effects = (Effect('special', 'heal minion', 1), ), description =__("This mysterious powder from the East will heal a minion's wounds or repair a magical artefact. Side effects may include dizziness, horniness, tentacles sprouting all over body.")),
                    Item(name = _('Cimerian scrap'), target = 'misc', type = IT_Misc, pic = 'Cimerian scrap.webp', sound=s_vibro, template = False, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 250, effects = (), description =__("A mysterious piece of ancient technological junk.")),
                    Item(name = _('Cimerian artefact'), target = 'misc', type = IT_Misc, pic = 'Cimerian artefact.webp', sound=s_vibro, template = False, rank = 1, max_rank = 5, rarity = 4, charges = 1, price = 1000, effects = (), description =__("A mysterious piece of ancient machinery. Also, junk.")),
                    Item(name = _("Lightning Rod"), target = 'MC', type = IT_Story, pic = "lightning rod.webp", template=False, rank=2, max_rank = 5, rarity=3, price = 1000, effects = (), description =__("Prevents lightning bolts from hurting you. It could save your ass in the right situation, although the chance to be hit by lightning while working in a brothel is very low. A syphilis rod might be more useful.")),

                    Item(name = _('White flower'), target = 'girl', type = IT_Flower, pic = 'White flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'white', 1), ), description ="白百合花象征着纯洁的爱情，别用你肮脏的思想玷污它！", hidden_effect = True),
                    Item(name = _('Yellow flower'), target = 'girl', type = IT_Flower, pic = 'Yellow flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'yellow', 1), ), description ="康乃馨能够驱逐病痛和悲伤，用它来抚慰少女受伤的心灵吧！", hidden_effect = True),
                    Item(name = _('Red flower'), target = 'girl', type = IT_Flower, pic = 'Red flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'red', 1), ), description ="玫瑰花可以用来泡浴，酿酒，香薰....难道你要用它表白？", hidden_effect = True),
                    Item(name = _('Green flower'), target = 'girl', type = IT_Flower, pic = 'Green flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'green', 1), ), description ="小小的绣球花可以戴在女孩的发髻旁，别有韵味。", hidden_effect = True),
                    Item(name = _('Blue flower'), target = 'girl', type = IT_Flower, pic = 'Blue flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'blue', 1), ), description ="矢车菊被风吹起时，就像自由的小鸟，自由是无价之宝。", hidden_effect = True),
                    Item(name = _('Orange flower'), target = 'girl', type = IT_Flower, pic = 'Orange flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'orange', 1), ), description ="郁金香被大面积地种植于农田中，微风轻拂~香飘十里。", hidden_effect = True),
                    Item(name = _('Purple flower'), target = 'girl', type = IT_Flower, pic = 'Purple flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'purple', 1), ), description ="紫罗兰代表了约定与等待，你是个守约的人吗？", hidden_effect = True),
                    Item(name = _('Pink flower'), target = 'girl', type = IT_Flower, pic = 'Pink flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'pink', 1), ), description ="芙蓉很适合那些含苞待放的少女们，爱恋之心逐渐生根发芽。", hidden_effect = True),
                    Item(name = _('Black flower'), target = 'girl', type = IT_Flower, pic = 'Black flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'black', 1), ), description ="曼陀罗象征着女性的自主与独立，她们勇敢、坚强。", hidden_effect = True),
                    ]


        # SPECIAL ITEMS AND FURNITURE #

        vitals_scanner = Furniture(_('Strange machine'), type='Gizmos', pic='scanner.webp', rank=2, chapter=2, cost=[('wood', 20), ('dye', 20), ('leather', 20)], duration=4, effects=[Effect("special", "autorest", 1, scope="brothel")], base_description="这个神秘的机器散发着一股奥术能量的波动。") #  It scans your girls automatically to make sure they are fit to work.

        billboard = Furniture(_('Clockwork billboard'), type='Furnishing', pic='billboard.webp', rank=2, chapter=2, cost=[('wood', 40), ('dye', 25), ('leather', 10)], duration=5, effects=[Effect("special", "advanced advertising", 1, scope="brothel")], base_description="这个华丽的广告牌能吸引许多人的注意。可以解锁高级广告设置。") #  Unlocks advanced advertising settings

        extractor_items = {"extractor1" : Item(name="Extractor Mk I", target="MC", type=IT_Story, pic="extractor1.webp", template = False, rarity = "S", price = 5000, effects=[], description =__("This strange steam machine lets you harvest wood, dye or leather automatically. Deploy on site.")),
                            "extractor2" : Item(name="Extractor Mk II", target="MC", type=IT_Story, pic="extractor2.webp", template = False, rarity = "S", price = 25000, effects=[], description =__("This strange steam machine lets you harvest marble, silk or ore automatically. Deploy on site.")),
                            }

        mizuki_kimono = Item(name = _("Mizuki's Kimono"), target = 'MC', type = IT_Story, pic = 'Kimono.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="dress", description =__("A kimono left behind by Mizuki Ike, the mysterious eldest Kunoichi."), hidden_effect = True).get_instance()

        subaru_tunic = Item(name = _("Subaru's Tunic"), target = 'girl', type = IT_Dress, pic = 'subaru tunic.webp', template = False, rank = 1, rarity = "S", price = 1000, effects = [Effect("special", "ignore energy", 1, chance=0.25)], description =__("Once worn by a fearsome kunoichi, this sturdy tunic is no longer of use to her."))

        makibishi = Item(name = _("Makibishi"), target = 'MC', type = IT_Misc, pic = 'bronze makibishi.webp', template = False, rank = 1, rarity = "S", price = 500, description =__("Automatically catches a Kunoichi when hunting ninjas (skip minigame)."), hidden_effect = True)
#                       Item(name = _("Iron Makibishi"), target = 'MC', type = IT_Story, pic = 'iron makibishi.webp', template = False, rank = 2, rarity = "S", price = 1000, description =__("Slows down Kunoichi movements during ninja hunt (medium effect)."), hidden_effect = True),
#                       Item(name = _("Steel Makibishi"), target = 'MC', type = IT_Story, pic = 'steel makibishi.webp', template = False, rank = 3, rarity = "S", price = 1500, description =__("Slows down Kunoichi movements during ninja hunt (large effect)."), hidden_effect = True),

        rep_item = Item(name = _("Royal Commendation"), target = "girl", type = IT_Misc, pic = 'edict.webp', template = False, rank = 1, rarity = "S", price = 1000, effects = [Effect("gain", "reputation", 10)], description =__("This honorific scroll bears the seal of the Pharo royal family. Proudly displayed in a girl's room, it is sure to get people's attention."))


        ## Already instantiated items (unique items, ready to add to MC inventory). This is important if direct inventory checks are done (item X in MC.items); Not recommended otherwise

        magic_notebook = Item(name = _('Magic notebook'), target = 'MC', type = IT_Passive, pic = 'Magic notebook.webp', template = False, rank = 1, rarity = "S", price = 0, effects = (Effect('special', 'notebook', 1), ), description =__("This handy notebook will store all the information you know about your girls. It magically writes down all your thoughts. Wait, don't think about {i}that{/i}... Too late."), hidden_effect = True).get_instance()

        toy_hammer = Item(name = _("Hammer Of Light"), target = 'MC', type = IT_Story, pic = 'toy hammer.webp', template = False, rank = 1, rarity = "S", price = 0, description =__("A diminutive 'warhammer' made of cheap materials. Supposed to work against the Kunoichi, but it looks like it couldn't even whack a mole."), hidden_effect = True).get_instance()

        mania_amulet = Item(name = _("Cheap charm"), target = 'MC', type = IT_Story, pic = 'cheap charm.webp', template = False, rank = 1, rarity = "S", price = 10, description =__("A cheap amulet found with a mysterious letter mentioning a club called 'Mania' in the guild quarter."), hidden_effect = True).get_instance()

        bast_letter = Item("Bast's love letter", "MC", type=IT_Story, pic="Scroll of etiquette.webp", template = False, rank = 1, rarity = "S", price = 0, effects = [], description =__("A love letter written by Bast to her former paramour. Contains incriminating information."), hidden_effect = True).get_instance()

        blueprint_item = Item(name = _('Ancient blueprint'), target = 'MC', type = IT_Story, pic = 'scanner blueprint.webp', template = False, rank = 1, rarity = "S", price = 0, effects = [], description =__("An ancient blueprint written on a light yet strong paper-like material. The instructions are foreign and indecipherable, but a skilled craftsman could perhaps make sense of it."), hidden_effect = True).get_instance()

        narika_hair = Item(name = _("Lock of Narika's hair"), target = 'MC', type = IT_Story, pic = 'hair.webp', template = False, rank = 1, rarity = "S", price = 0, description =__("A lock of pink hair, belonging to the Kunoichi prodigy Narika Shihoudou."), hidden_effect = True).get_instance()

        blue_ribbon = Item(name = _("Homura's ribbon"), target = 'MC', type = IT_Story, pic = 'blue ribbon.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="necklace", description =__("A ribbon given to you by Lady Henso. Tie it to a pole in the city {b}Plaza{/b} to let her know you want to see her."), hidden_effect = True).get_instance()

        earth_rune = Item(name = _("Earth Rune"), target = 'MC', type = IT_Story, pic = 'earth rune.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="misc", description =__("This runestone has a strong inhibitive effect on Earth magic and disorients their users. This could help you out against the Earth ninja."), hidden_effect = True).get_instance()
        water_rune = Item(name = _("Water Rune"), target = 'MC', type = IT_Story, pic = 'water rune.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="misc", description =__("This runestone has a strong inhibitive effect on Water magic and disorients their users. This could help you out against the Water ninja."), hidden_effect = True).get_instance()
        void_rune = Item(name = _("Void Rune"), target = 'MC', type = IT_Story, pic = 'void rune.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="misc", description =__("This runestone can manipulate time to slow down super fast people and objects, or something. This could help you out against the Void ninja."), hidden_effect = True).get_instance()
        fire_rune = Item(name = _("Fire Rune"), target = 'MC', type = IT_Story, pic = 'fire rune.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="misc", description =__("This runestone has a strong inhibitive effect on Fire magic and disorients their users. You don't know any Fire magic users, so would that really be useful to you?"), hidden_effect = True).get_instance()

        MU_entry_scroll = Item(name = _("M.U. registration scroll"), target = 'MC', type = IT_Story, pic = 'Scroll of Gomorrah.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="misc", description =__("This scroll gives you access to the Magic University for a week."), hidden_effect = True).get_instance()

        # Chaos

        chaos_full_charge = Item(name = _('Full Power Chaos'), target = 'MC', type = IT_Weapon, sellable=False, giveable=False, pic = 'Demon sword.webp', rank = 4, rarity = "S", price = 0, effects = (Effect('change', 'strength', 4), Effect('change', 'charisma', 4), Effect('change', 'spirit', 4)), description =__("The blade pulses with the dark fury of the greater daemon trapped inside. It refills its energy from cavorting with girls, somehow. It is fully charged.")).get_instance()
        chaos_high_charge = Item(name = _('Mid Power Chaos'), target = 'MC', type = IT_Weapon, sellable=False, giveable=False, pic = 'Demon sword.webp', rank = 4, rarity = "S", price = 0, effects = (Effect('change', 'strength', 3), Effect('change', 'charisma', 3), Effect('change', 'spirit', 3)), description =__("The blade pulses with the dark fury of the greater daemon trapped inside. It refills its energy from cavorting with girls, somehow. It is well charged.")).get_instance()
        chaos_low_charge = Item(name = _('Low Power Chaos'), target = 'MC', type = IT_Weapon, sellable=False, giveable=False, pic = 'Demon sword.webp', rank = 4, rarity = "S", price = 0, effects = (Effect('change', 'strength', 2), Effect('change', 'charisma', 2), Effect('change', 'spirit', 2)), description =__("The blade pulses with the dark fury of the greater daemon trapped inside. It refills its energy from cavorting with girls, somehow. It is partially charged.")).get_instance()
        chaos_no_charge = Item(name = _('Depleted Chaos'), target = 'MC', type = IT_Weapon, sellable=False, giveable=False, pic = 'Demon sword.webp', rank = 4, rarity = "S", price = 0, effects = (Effect('change', 'strength', 1), Effect('change', 'charisma', 1), Effect('change', 'spirit', 1)), description =__("The blade pulses with the dark fury of the greater daemon trapped inside. It refills its energy from cavorting with girls, somehow. It is not charged.")).get_instance()

        # NG+ items (do not instantiate)

        seduction_potion = Item(name = _("Potion of Seduction"), target = 'gift', type = IT_Gift, pic = 'love potion.webp', template = False, rank = 1, rarity = "S", price = 0, effects = [Effect("potion", "seduction", 1)], pic_dir="misc", description =__("This potion raises the relationship level with any free girl in the city to the next step."), sound = s_bubbling, hidden_effect = True)
        restoration_balm = Item(name = _("Balm of Restoration"), target = 'girl', type = IT_Misc, pic = 'monster juice.webp', template = False, rank = 1, rarity = "S", price = 0, effects = [Effect("special", "virginity", 1)], pic_dir="misc", description =__("This balm is prized by the nobility. It restores a girl's virginity (in appearance, anyway)."), sound = s_dress, hidden_effect = True)
        bliss_incense = Item(name = _("Incense of Bliss"), target = 'girl', type = IT_Misc, pic = 'extractor2.webp', template = False, rank = 1, rarity = "S", price = 0, effects = [Effect("special", "sanity", 1)], pic_dir="misc", description =__("This exotic drug helps forget even the worst traumas."), sound = s_fire, hidden_effect = True)
        magic_powder = Item(name = _("Magic Powder"), target = 'MC', type = IT_Misc, pic = 'healing powder.webp', template = False, rank = 1, rarity = "S", price = 0, effects = [Effect("special", "MC interactions", 1)], pic_dir="misc", description =__("Snort some to recover all of your AP and Mana. It's completely legal. Maybe."), sound = s_maniacal_laugh, hidden_effect = True)
        wyvern_egg = Item(name = _('Wyvern egg'), target = 'girl', type = IT_Misc, pic = 'Wyvern egg.webp', template = False, rank = 1, rarity = "S", charges = 1, price = 10000, sellable=False, effects = (Effect('gain', 'perk', 1), ), description =__("A dish fit for a brothel queen."), sound = s_roar) # Also used in events/gift shop


    ### TEMPLATE ITEMS ###

        template_items = [
                            Item(name = _('Stolen underwear'), target = 'MC', type = IT_Misc, pic = 'Stolen underwear.webp', template = True, rank = 1, max_rank = 5, rarity = "S", charges = 1, price = 500, effects = (Effect('gain', 'prestige', 2), ), description =__("So you're into these, eh?")),
                            Item(name = _('Romantic novel'), target = 'gift', type = IT_Gift, pic = 'Romantic novel.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'cute', 1), Effect('gift', 'book', 1), ), description =__(  "A knight in shining armor. A princess. A plumber. The usual."), hidden_effect = True),
                            Item(name = _('Erotic manual'), target = 'gift', type = IT_Gift, pic = 'Erotic manual.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'erotica', 1), Effect('gift', 'book', 1), ), description =__(  "50 positions that you can only achieve using black magic."), hidden_effect = True),
                            Item(name = _('Goldleaf book'), target = 'gift', type = IT_Gift, pic = 'Goldleaf book.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'precious', 1), Effect('gift', 'book', 1), ), description =__(  "What does it talk about? Who cares! It's shiny."), hidden_effect = True),
                            Item(name = _('Book of magical cocktails'), target = 'gift', type = IT_Gift, pic = 'Book of magical cocktails.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'drinks', 1), Effect('gift', 'book', 1), ), description =__(  "Warning: consuming those potions may result in loss of memory. Also,  dignity."), hidden_effect = True),
                            Item(name = _('Pet'), target = 'gift', type = IT_Gift, pic = 'Pet.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'cute', 1), Effect('gift', 'precious', 1), ), description =__(  "Isn't he adorable? As long as he doesn't bite your hand off..."), hidden_effect = True),
                            Item(name = _('Silky nighties'), target = 'gift', type = IT_Gift, pic = 'Silky nighties.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'cute', 1), Effect('gift', 'erotica', 1), ), description =__(  "Smooth and sexy."), hidden_effect = True),
                            Item(name = _('Sakura liquor'), target = 'gift', type = IT_Gift, pic = 'Sakura liquor.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'cute', 1), Effect('gift', 'drinks', 1), ), description =__(  "A subtle drink made of distilled flower petals."), hidden_effect = True),
                            Item(name = _('Sexy high heels'), target = 'gift', type = IT_Gift, pic = 'Sexy high heels.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'erotica', 1), Effect('gift', 'precious', 1), ), description =__(  "Some women would kill to get their hands on those shoes. Actually,  they're a little blood spattered."), hidden_effect = True),
                            Item(name = _('Champagne'), target = 'gift', type = IT_Gift, pic = 'Champagne.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'drinks', 1), Effect('gift', 'precious', 1), ), description =__(  "'Le Nouveau Riche': A strong drink; also, a statement that you can afford it."), hidden_effect = True),
                            Item(name = _('Aphrodisiac'), target = 'gift', type = IT_Gift, pic = 'Aphrodisiac.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'drinks', 1), Effect('gift', 'erotica', 1), ), description =__(  "Fire in your belly,  fire in your pants..."), hidden_effect = True),
                            Item(name = _('Pretty ring'), target = 'girl', type = IT_Ring, pic = 'Pretty ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 150, effects = (Effect('change', 'beauty', 5), ), ),
                            Item(name = _('Bronze ring'), target = 'girl', type = IT_Ring, pic = 'Bronze ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 150, effects = (Effect('change', 'body', 5), ), ),
                            Item(name = _('Zanic ring'), target = 'girl', type = IT_Ring, pic = 'Zanic ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 150, effects = (Effect('change', 'charm', 5), ), ),
                            Item(name = _('Silver ring'), target = 'girl', type = IT_Ring, pic = 'Silver ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 150, effects = (Effect('change', 'refinement', 5), ), ),
                            Item(name = _('Gold ring'), target = 'girl', type = IT_Ring, pic = 'Gold ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('change', 'libido', 5), ), ),
                            Item(name = _('Marine ring'), target = 'girl', type = IT_Ring, pic = 'Marine ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('change', 'sensitivity', 5), ), ),
                            Item(name = _('Iron ring'), target = 'girl', type = IT_Ring, pic = 'Iron ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 375, effects = (Effect('change', 'obedience', 5), ), ),
                            Item(name = _('Wooden ring'), target = 'girl', type = IT_Ring, pic = 'Wooden ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('change', 'constitution', 5), ), ),
                            Item(name = _('Blue ribbon'), target = 'girl', type = IT_Necklace, pic = 'Blue ribbon.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 100, effects = (Effect('boost', 'beauty gains', 0.1), ), ),
                            Item(name = _('Pearl necklace'), target = 'girl', type = IT_Necklace, pic = 'Pearl necklace.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 100, effects = (Effect('boost', 'body gains', 0.1), ), ),
                            Item(name = _('Moon necklace'), target = 'girl', type = IT_Necklace, pic = 'Moon necklace.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 100, effects = (Effect('boost', 'charm gains', 0.1), ), ),
                            Item(name = _('Ivory necklace'), target = 'girl', type = IT_Necklace, pic = 'Ivory necklace.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 100, effects = (Effect('boost', 'refinement gains', 0.1), ), ),
                            Item(name = _('Choker necklace'), target = 'girl', type = IT_Necklace, pic = 'Choker necklace.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('boost', 'libido gains', 0.1), ), ),
                            Item(name = _('Dog collar'), target = 'girl', type = IT_Necklace, pic = 'Dog collar.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('boost', 'obedience gains', 0.1), ), ),
                            Item(name = _('Silver chain'), target = 'girl', type = IT_Necklace, pic = 'Silver chain.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('boost', 'sensitivity gains', 0.1), ), ),
                            Item(name = _('Dagger necklace'), target = 'girl', type = IT_Necklace, pic = 'Dagger necklace.webp', template = True, rank = 1, max_rank = 5, rarity = 2, price = 250, effects = (Effect('boost', 'constitution gains', 0.1), ), ),
                            Item(name = _('Gold bag'), target = 'girl', type = IT_Misc, pic = 'Gold bag.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 600, effects = (Effect('special', 'level', 5), ), description =__(  "Instant level up. Use it wisely..."), adjectives = "ring"),
                            Item(name = _('Jewel bag'), target = 'girl', type = IT_Misc, pic = 'Jewel bag.webp', template = True, rank = 1, max_rank = 5, rarity = 3, charges = 1, price = 500, effects = (Effect('gain', 'skill points', 5), ), description =__(  "Get extra skill points.")),
                            Item(name = _('Knowledge scroll'), target = 'girl', type = IT_Misc, pic = 'Knowledge scroll.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 400, effects = (Effect('gain', 'xp', 50), ), description =__(  "Get free xp."), adjectives = "scroll"),
                            Item(name = _('Medicine bag'), target = 'girl', type = IT_Misc, pic = 'Medicine bag.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 250, effects = (Effect('instant', 'heal', 2), ), description =__(  "")),
                            Item(name = _('Tonic'), target = 'girl', type = IT_Misc, pic = 'Tonic.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 75, effects = (Effect('gain', 'energy', 20), ), description =__(  "")),
                            Item(name = _('Wine'), target = 'girl', type = IT_Misc, pic = 'Wine.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 75, effects = (Effect('gain', 'mood', 10), ), description =__(  "")),
                            Item(name = _('Apple'), target = 'girl', type = IT_Food, pic = 'Apple.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 50, effects = (Effect('change', 'beauty', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), description =__(  "An apple a day keeps the doctor away.")),
                            Item(name = _('Pear'), target = 'girl', type = IT_Food, pic = 'Pear.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 50, effects = (Effect('change', 'body', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Peach'), target = 'girl', type = IT_Food, pic = 'Peach.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 50, effects = (Effect('change', 'charm', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Grapes'), target = 'girl', type = IT_Food, pic = 'Grapes.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 50, effects = (Effect('change', 'refinement', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Sausage'), target = 'girl', type = IT_Food, pic = 'Sausage.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 75, effects = (Effect('change', 'libido', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Cheese'), target = 'girl', type = IT_Food, pic = 'Cheese.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 75, effects = (Effect('change', 'sensitivity', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Chicken'), target = 'girl', type = IT_Food, pic = 'Chicken.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 90, effects = (Effect('change', 'obedience', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Roastbeef'), target = 'girl', type = IT_Food, pic = 'Roastbeef.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 75, effects = (Effect('change', 'constitution', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Love potion'), target = 'girl', type = IT_Misc, pic = 'Love potion.webp', template = True, rank = 1, max_rank = 6, rarity = 2, charges = 1, price = 100, effects = (Effect('gain', 'love', 2.5), ), description =__("Who said money can't buy you love?")),
                            Item(name = _('Monster juice'), target = 'girl', type = IT_Misc, pic = 'Monster juice.webp', template = True, rank = 1, max_rank = 6, rarity = 2, charges = 1, price = 60, effects = (Effect('gain', 'fear', 2.5), ), description =__("You don't want to know from which monster body parts this came from.")),
                            Item(name = _('Pink panties'), target = 'girl', type = IT_Accessory, pic = 'Pink panties.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 125, effects = (Effect('change', 'beauty', 5), ), ),
                            Item(name = _('Hot pants'), target = 'girl', type = IT_Accessory, pic = 'Hot pants.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 125, effects = (Effect('change', 'body', 5), ), ),
                            Item(name = _('Lowcut panties'), target = 'girl', type = IT_Accessory, pic = 'Lowcut panties.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 125, effects = (Effect('change', 'charm', 5), ), ),
                            Item(name = _('Lace panties'), target = 'girl', type = IT_Accessory, pic = 'Lace panties.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 125, effects = (Effect('change', 'refinement', 5), ), ),
                            Item(name = _('Sexy panties'), target = 'girl', type = IT_Accessory, pic = 'Sexy panties.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('change', 'libido', 5), ), ),
                            Item(name = _('Seethrough panties'), target = 'girl', type = IT_Accessory, pic = 'Seethrough panties.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('change', 'sensitivity', 5), ), ),
                            Item(name = _('Chastity belt'), target = 'girl', type = IT_Accessory, pic = 'Chastity belt.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 350, effects = (Effect('change', 'obedience', 5), ), ),
                            Item(name = _('Thong'), target = 'girl', type = IT_Accessory, pic = 'Thong.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 175, effects = (Effect('change', 'constitution', 5), ), ),
                            Item(name = _('Bunny suit'), target = 'girl', type = IT_Dress, pic = 'Bunny suit.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 250, effects = (Effect('change', 'body', 5), Effect('change', 'libido', 5), ), ),
                            Item(name = _('Guard uniform'), target = 'girl', type = IT_Dress, pic = 'Guard uniform.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 250, effects = (Effect('change', 'charm', 5), Effect('change', 'constitution', 5), ), ),
                            Item(name = _('School uniform'), target = 'girl', type = IT_Dress, pic = 'School uniform.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 250, effects = (Effect('change', 'beauty', 5), Effect('change', 'libido', 5), ), ),
                            Item(name = _('Bikini'), target = 'girl', type = IT_Dress, pic = 'Bikini.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 250, effects = (Effect('change', 'body', 5), Effect('change', 'constitution', 5), ), ),
                            Item(name = _('Kimono'), target = 'girl', type = IT_Dress, pic = 'Kimono.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 350, effects = (Effect('change', 'refinement', 5), Effect('change', 'obedience', 5), ), ),
                            Item(name = _('Swimsuit'), target = 'girl', type = IT_Dress, pic = 'Swimsuit.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 250, effects = (Effect('change', 'beauty', 5), Effect('change', 'sensitivity', 5), ), ),
                            Item(name = _('Frilly dress'), target = 'girl', type = IT_Dress, pic = 'Frilly dress.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 250, effects = (Effect('change', 'charm', 5), Effect('change', 'sensitivity', 5), ), ),
                            Item(name = _('Leather dress'), target = 'girl', type = IT_Dress, pic = 'Leather dress.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 250, effects = (Effect('change', 'constitution', 5), Effect('change', 'obedience', 5), ), ),
                            Item(name = _('Evening gown'), target = 'girl', type = IT_Dress, pic = 'Evening gown.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 400, effects = (Effect('change', 'beauty', 5), Effect('change', 'charm', 5), Effect('change', 'refinement', 5), Effect('change', 'body', -5), ), ),
                            Item(name = _('Silk dress'), target = 'girl', type = IT_Dress, pic = 'Silk dress.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 400, effects = (Effect('change', 'libido', 5), Effect('change', 'sensitivity', 5), Effect('change', 'obedience', 5), Effect('change', 'constitution', -5), ), ),
                            Item(name = _('Pompom uniform'), target = 'girl', type = IT_Dress, pic = 'Pompom uniform.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 400, effects = (Effect('change', 'beauty', 5), Effect('change', 'charm', 5), Effect('change', 'body', 5), Effect('change', 'refinement', -5), ), ),
                            Item(name = _('Knight uniform'), target = 'girl', type = IT_Dress, pic = 'Knight uniform.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 400, effects = (Effect('change', 'body', 5), Effect('change', 'constitution', 5), Effect('change', 'obedience', 5), Effect('change', 'libido', -5), ), ),
                            Item(name = _('Black slavekini'), target = 'girl', type = IT_Dress, pic = 'Black slavekini.webp', template = True, rank = 1, max_rank = 6, rarity = "S", price = 750, effects = (Effect('change', 'beauty', 5), Effect('change', 'body', 5), Effect('change', 'charm', 5), Effect('change', 'refinement', 5), ), ),
                            Item(name = _('Blue slavekini'), target = 'girl', type = IT_Dress, pic = 'Blue slavekini.webp', template = True, rank = 1, max_rank = 6, rarity = "S", price = 1000, effects = (Effect('change', 'libido', 5), Effect('change', 'sensitivity', 5), Effect('change', 'obedience', 5), Effect('change', 'constitution', 5), ), ),
                            Item(name = _('Red slavekini'), target = 'girl', type = IT_Dress, pic = 'Red slavekini.webp', template = True, rank = 1, max_rank = 6, rarity = "S", price = 2000, effects = (Effect('change', 'service', 5), Effect('change', 'sex', 5), Effect('change', 'anal', 5), Effect('change', 'fetish', 5), ), ),
                            Item(name = _('Sunny dress'), target = 'girl', type = IT_Dress, pic = 'Sunny dress.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 300, effects = (Effect('change', 'beauty', 10), ), ),
                            Item(name = _('Revealing dress'), target = 'girl', type = IT_Dress, pic = 'Revealing dress.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 300, effects = (Effect('change', 'body', 10), ), ),
                            Item(name = _('Exotic dress'), target = 'girl', type = IT_Dress, pic = 'Exotic dress.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 300, effects = (Effect('change', 'charm', 10), ), ),
                            Item(name = _('Priestess robe'), target = 'girl', type = IT_Dress, pic = 'Priestess robe.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 300, effects = (Effect('change', 'refinement', 10), ), ),
                            Item(name = _('Slutty dress'), target = 'girl', type = IT_Dress, pic = 'Slutty dress.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 425, effects = (Effect('change', 'libido', 10), ), ),
                            Item(name = _('Seethrough dress'), target = 'girl', type = IT_Dress, pic = 'Seethrough dress.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 425, effects = (Effect('change', 'sensitivity', 10), ), ),
                            Item(name = _('Maid uniform'), target = 'girl', type = IT_Dress, pic = 'Maid uniform.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 500, effects = (Effect('change', 'obedience', 10), ), ),
                            Item(name = _('Gym uniform'), target = 'girl', type = IT_Dress, pic = 'Gym uniform.webp', template = True, rank = 0, max_rank = 6, rarity = 0, price = 425, effects = (Effect('change', 'constitution', 10), ), ),
                            Item(name = _('Emerald ring'), target = 'girl', type = IT_Ring, pic = 'Emerald ring.webp', template = True, rank = 1, max_rank = 5, rarity = 3, price = 500, effects = (Effect('change', 'service', 5), ), ),
                            Item(name = _('Ruby ring'), target = 'girl', type = IT_Ring, pic = 'Ruby ring.webp', template = True, rank = 1, max_rank = 5, rarity = 3, price = 500, effects = (Effect('change', 'sex', 5), ), ),
                            Item(name = _('Amber ring'), target = 'girl', type = IT_Ring, pic = 'Amber ring.webp', template = True, rank = 1, max_rank = 5, rarity = 3, price = 500, effects = (Effect('change', 'anal', 5), ), ),
                            Item(name = _('Sapphire ring'), target = 'girl', type = IT_Ring, pic = 'sapphire ring.webp', template = True, rank = 1, max_rank = 5, rarity = 3, price = 500, effects = (Effect('change', 'fetish', 5), ), ),
                            Item(name = _('Scroll of bartending'), target = 'girl', type = IT_Misc, pic = 'Scroll of bartending.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'waitress jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of whirling'), target = 'girl', type = IT_Misc, pic = 'Scroll of whirling.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'dancer jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of rubbing'), target = 'girl', type = IT_Misc, pic = 'Scroll of rubbing.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'masseuse jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of etiquette'), target = 'girl', type = IT_Misc, pic = 'Scroll of etiquette.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'geisha jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of Onan'), target = 'girl', type = IT_Misc, pic = 'Scroll of Onan.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'service jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of Eros'), target = 'girl', type = IT_Misc, pic = 'Scroll of Eros.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'sex jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of Sodom'), target = 'girl', type = IT_Misc, pic = 'Scroll of Sodom.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'anal jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of Gomorrah'), target = 'girl', type = IT_Misc, pic = 'Scroll of Gomorrah.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'fetish jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Elvish-made penis enlarger'), target = 'minion', type = IT_Misc, pic = 'enlarger.webp', template = True, rank = 1, max_rank = 5, rarity = "M", charges = 1, price = 120, effects = (Effect('gain', 'stallion xp', 10), ), description =__("That's not mine. This sort of thing ain't my bag, baby!")),
                            Item(name = _('Machine lubricant'), target = 'minion', type = IT_Misc, pic = 'lubricant.webp', template = True, rank = 1, max_rank = 5, rarity = "M", charges = 1, price = 120, effects = (Effect('gain', 'machine xp', 10), ), description =__("Grease is good.")),
                            Item(name = _('Strange feed'), target = 'minion', type = IT_Misc, pic = 'feed.webp', template = True, rank = 1, max_rank = 5, rarity = "M", charges = 1, price = 120, effects = (Effect('gain', 'beast xp', 10), ), description =__("Like it when they hold onto your leg and rubs themselves up and down? Because this feed sure makes them wanna do that.")),
                            Item(name = _('Monster cookie'), target = 'minion', type = IT_Misc, pic = 'cookie.webp', template = True, rank = 1, max_rank = 5, rarity = "M", charges = 1, price = 120, effects = (Effect('gain', 'monster xp', 10), ), description =__("C is for cock-y."), adjectives = "food"),

                            Item(name = '羽毛内衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '羽毛内衣 (1).webp', '羽毛内衣 (2).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 , effects = (Effect('change', 'libido', 6), Effect('change', 'service', 6), ), description = "用好看的羽毛制作而成的内衣，可能会有点痒。"),
                            Item(name = '珍珠内衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '珍珠内衣 (1).webp', '珍珠内衣 (2).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 , effects = (Effect('change', 'sensitivity', 6), Effect('change', 'sex', 6), ), description = "用串联的珍珠挡住私密的部位，小珍珠挡得住大珍珠吗？"),
                            Item(name = '渔网内衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '渔网内衣 (1).webp', '渔网内衣 (2).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 , effects = (Effect('change', 'constitution', 6), Effect('change', 'anal', 6), ), description = "知名探险家贝尔格里斯曾用这种内衣捕捞到了一条大鱼，质量可靠。"),
                            Item(name = '透明内衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '透明内衣 (1).webp', '透明内衣 (2).webp', '透明内衣 (3).webp', '透明内衣 (4).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 , effects = (Effect('change', 'obedience', 6), Effect('change', 'fetish', 6), ), description = "这和没穿又有什么区别呢？可能是摸上去的质感不同吧。"),
                            
                            Item(name = '可撕内衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '可撕内衣 (1).webp', '可撕内衣 (2).webp', '可撕内衣 (3).webp', '可撕内衣 (4).webp', '可撕内衣 (5).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 750 , effects = (Effect('change', 'libido', 6), Effect('change', 'sensitivity', 6), ), description = "设计师在特别的部位选用了特别的面料，方便行事。就是用完了得重新买。"),
                            Item(name = '蕾丝内衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '蕾丝内衣 (1).webp', '蕾丝内衣 (2).webp', '蕾丝内衣 (3).webp', '蕾丝内衣 (4).webp', '蕾丝内衣 (5).webp', '蕾丝内衣 (6).webp', '蕾丝内衣 (7).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 750 , effects = (Effect('change', 'constitution', 6), Effect('change', 'obedience', 6), ), description = "这种贴身的丝滑而又柔软的内衣，饱受女士和男士好评。"),
                            Item(name = '网纱内衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '网纱内衣 (1).webp', '网纱内衣 (2).webp', '网纱内衣 (3).webp', '网纱内衣 (4).webp', '网纱内衣 (5).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 750 , effects = (Effect('change', 'sex', 6), Effect('change', 'anal', 6), ), description = "多么贴心的设计，方便你把手从各个位置插进去。"),
                            Item(name = '亮片内衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '亮片内衣 (1).webp', '亮片内衣 (2).webp', '亮片内衣 (3).webp', '亮片内衣 (4).webp', '亮片内衣 (5).webp', '亮片内衣 (6).webp', '亮片内衣 (7).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 750 , effects = (Effect('change', 'service', 6), Effect('change', 'fetish', 6), ), description = "闪亮的亮片在灯光下是那么耀眼，这会让女孩更加光彩动人。"),
                            
                            Item(name = '护士制服®', target = 'girl', type = IT_Dress, pic=random.choice([ '护士制服 (1).webp', '护士制服 (2).webp']), template = True, rank = 2, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('change', 'charm', 12), ), description = "这次轮到你给护士“打针”了。"),
                            Item(name = '奶牛装®', target = 'girl', type = IT_Dress, pic=random.choice([ '奶牛装.webp']), template = True, rank = 2, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('change', 'beauty', 12), ), description = "沉甸甸的果实悬挂在胸前，她需要一位熟练的挤奶工帮忙释放压力。"),
                            Item(name = '赛车女郎®', target = 'girl', type = IT_Dress, pic=random.choice([ '赛车女郎.webp']), template = True, rank = 2, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('change', 'body', 12), ), description = "三、二、一，出发！什么？你被她的车灯给晃住了？"),
                            Item(name = '教师制服®', target = 'girl', type = IT_Dress, pic=random.choice([ '教师制服 (1).webp', '教师制服 (2).webp']), template = True, rank = 2, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('change', 'refinement', 12), ), description = "家庭教师要给你上生理课了哦~"),
                            
                            Item(name = '裸体围裙®', target = 'girl', type = IT_Dress, pic=random.choice([ '裸体围裙.webp']), template = True, rank = 2, max_rank = 6, rarity = 1, price = 900 , effects = (Effect('change', 'libido', 12), ), description = "在做饭的时候不要在背后打扰她，至少，先把火关了。"),
                            Item(name = '乳首夹®', target = 'girl', type = IT_Dress, pic=random.choice([ '乳首夹.webp']), template = True, rank = 2, max_rank = 6, rarity = 1, price = 900 , effects = (Effect('change', 'constitution', 12), ), description = "这能使乳首始终保持挺立。"),
                            Item(name = '眼罩®', target = 'girl', type = IT_Dress, pic=random.choice([ '眼罩.webp']), template = True, rank = 2, max_rank = 6, rarity = 1, price = 900 , effects = (Effect('change', 'sensitivity', 12), ), description = "人在失去视觉时触觉会变得更加敏感。"),
                            Item(name = '蕾丝内裤®', target = 'girl', type = IT_Dress, pic=random.choice([ '蕾丝内裤 (1).webp', '蕾丝内裤 (2).webp', '蕾丝内裤 (3).webp', '蕾丝内裤 (4).webp']), template = True, rank = 2, max_rank = 6, rarity = 1, price = 900 , effects = (Effect('change', 'obedience', 12), ), description = "透气透光的蕾丝设计，遮盖住了神秘的森林。"),

                            Item(name = '丝袜®', target = 'girl', type = IT_Dress, pic=random.choice([ '丝袜 (1).webp', '丝袜 (2).webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1200 , effects = (Effect('change', 'service', 12), ), description = "不管黑丝白丝，答应我，别脱下来好吗？"),
                            Item(name = '乳贴®', target = 'girl', type = IT_Dress, pic=random.choice([ '乳贴 (1).webp', '乳贴 (2).webp', '乳贴 (3).webp', '乳贴 (4).webp', '乳贴 (5).webp', '乳贴 (6).webp', '乳贴 (7).webp', '乳贴 (8).webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1200 , effects = (Effect('change', 'sex', 12), ), description = "创口贴，胶带，贴纸....小技巧：乳头挺立时更容易撕下来。"),
                            Item(name = '绑带®', target = 'girl', type = IT_Dress, pic=random.choice([ '绑带 (1).webp', '绑带 (2).webp', '绑带 (3).webp', '绑带 (4).webp', '绑带 (5).webp', '绑带 (6).webp', '绑带 (7).webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1200 , effects = (Effect('change', 'anal', 12), ), description = "紧紧的缠在胸前，等待有缘人释放被束缚的巨峰。"),
                            Item(name = '浴巾®', target = 'girl', type = IT_Dress, pic=random.choice([ '浴巾 (1).webp', '浴巾 (2).webp', '浴巾 (3).webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1200 , effects = (Effect('change', 'fetish', 12), ), description = "特制浴巾，表面的活性绒毛接触到皮肤上能给你触电般的快感。"),
                            
                            Item(name = '睡袍®', target = 'girl', type = IT_Dress, pic=random.choice([ '睡袍.webp']), template = True, rank = 2, max_rank = 6, rarity = 3, price = 1500 , effects = (Effect('change', 'beauty', 5), Effect('change', 'charm', 12), Effect('change', 'refinement', 6), Effect('change', 'body', 6), Effect('special', 'lucky', 1), ), description = "林品如同款睡衣，既然要追求刺激，那就贯彻到底吧！"),
                            Item(name = '婚纱®', target = 'girl', type = IT_Dress, pic=random.choice([ '婚纱 (1).webp', '婚纱 (2).webp', '婚纱 (3).webp', '婚纱 (4).webp', '婚纱 (5).webp']), template = True, rank = 2, max_rank = 6, rarity = 3, price = 1500 , effects = (Effect('change', 'beauty', 12), Effect('change', 'charm', 6), Effect('change', 'refinement', 5), Effect('change', 'body', 6), Effect('special', 'lucky', 1), ), description = "有的人喜欢中式，有的人喜欢西式，不过到了床上反正都要脱掉，又有什么区别呢？"),
                            Item(name = '晚礼服®', target = 'girl', type = IT_Dress, pic=random.choice([ '晚礼服 (1).webp', '晚礼服 (2).webp', '晚礼服 (3).webp', '晚礼服 (4).webp', '晚礼服 (5).webp']), template = True, rank = 2, max_rank = 6, rarity = 3, price = 1500 , effects = (Effect('change', 'beauty', 6), Effect('change', 'charm', 6), Effect('change', 'refinement', 5), Effect('change', 'body', 12), Effect('special', 'lucky', 1), ), description = "选用顶级的面料，尽享奢华，成为宴会上的一道风景线吧！"),
                            Item(name = '轻纱®', target = 'girl', type = IT_Dress, pic=random.choice([ '轻纱 (1).webp', '轻纱 (2).webp', '轻纱 (3).webp', '轻纱 (4).webp', '轻纱 (5).webp', '轻纱 (6).webp']), template = True, rank = 2, max_rank = 6, rarity = 3, price = 1500 , effects = (Effect('change', 'beauty', 6), Effect('change', 'charm', 6), Effect('change', 'refinement', 12), Effect('change', 'body', 6), Effect('special', 'lucky', 1), ), description = "透过轻纱能够隐约看见她诱人的胴体，如果刮起一阵风的话...."),
                            
                            Item(name = '乳首跳蛋®', target = 'girl', type = IT_Dress, pic=random.choice([ '乳首跳蛋 (1).webp', '乳首跳蛋 (2).webp', '乳首跳蛋 (3).webp']), template = True, rank = 3, max_rank = 6, rarity = 4, price = 3000 , effects = (Effect('change', 'service', 12), Effect('change', 'sex', 6), Effect('change', 'anal', 6), Effect('change', 'fetish', 6), Effect('special', 'lucky', 2), ), description = "嗡——嗡——，放心，不是你的电话响了。"),
                            Item(name = '肥皂泡泡®', target = 'girl', type = IT_Dress, pic=random.choice([ '肥皂泡泡 (1).webp', '肥皂泡泡 (2).webp']), template = True, rank = 3, max_rank = 6, rarity = 4, price = 3000 , effects = (Effect('change', 'service', 5), Effect('change', 'sex', 12), Effect('change', 'anal', 6), Effect('change', 'fetish', 6), Effect('special', 'lucky', 2), ), description = "这种特别调制的泡沫可以维持很久而不消散。"),
                            Item(name = '魅魔淫纹®', target = 'girl', type = IT_Dress, pic=random.choice([ '魅魔淫纹 (1).webp', '魅魔淫纹 (2).webp']), template = True, rank = 3, max_rank = 6, rarity = 4, price = 3000 , effects = (Effect('change', 'service', 5), Effect('change', 'sex', 6), Effect('change', 'anal', 12), Effect('change', 'fetish', 6), Effect('special', 'lucky', 2), ), description = "将这种纹章贴纸贴在小腹上，你会得到魅魔的祝福的。"),
                            Item(name = '人体彩绘®', target = 'girl', type = IT_Dress, pic=random.choice([ '人体彩绘 (1).webp', '人体彩绘 (2).webp']), template = True, rank = 3, max_rank = 6, rarity = 4, price = 3000 , effects = (Effect('change', 'service', 5), Effect('change', 'sex', 6), Effect('change', 'anal', 6), Effect('change', 'fetish', 12), Effect('special', 'lucky', 2), ), description = "对于暴露狂来说既能满足裸体的需求，又不至于让别人不好意思看。"),
                            
                            Item(name = '开胸装®', target = 'girl', type = IT_Dress, pic=random.choice([ '开胸装 (1).webp', '开胸装 (2).webp', '开胸装 (3).webp', '开胸装 (4).webp']), template = True, rank = 3, max_rank = 6, rarity = 3, price = 2400 , effects = (Effect('change', 'libido', 12), Effect('change', 'sensitivity', 6), Effect('change', 'obedience', 6), Effect('change', 'constitution', 6), ), description = "适合哺乳期妈妈的着装，谁还不是个小宝贝了~"),
                            Item(name = '男友衬衫®', target = 'girl', type = IT_Dress, pic=random.choice([ '男友衬衫 (1).webp', '男友衬衫 (2).webp', '男友衬衫 (3).webp', '男友衬衫 (4).webp']), template = True, rank = 3, max_rank = 6, rarity = 3, price = 2400 , effects = (Effect('change', 'libido', 5), Effect('change', 'sensitivity', 12), Effect('change', 'obedience', 5), Effect('change', 'constitution', 6), ), description = "重点是尺寸不合身，不管是尺寸过大还是过小，都别有一番风味。"),
                            Item(name = '裹身裙®', target = 'girl', type = IT_Dress, pic=random.choice([ '裹身裙 (1).webp', '裹身裙 (2).webp', '裹身裙 (3).webp', '裹身裙 (4).webp', '裹身裙 (5).webp', '裹身裙 (6).webp', '裹身裙 (7).webp', '裹身裙 (8).webp']), template = True, rank = 3, max_rank = 6, rarity = 3, price = 2400 , effects = (Effect('change', 'libido', 6), Effect('change', 'sensitivity', 6), Effect('change', 'obedience', 12), Effect('change', 'constitution', 6), ), description = "紧紧的裹住身体，勾勒出诱人的身材曲线。"),
                            Item(name = '露背装®', target = 'girl', type = IT_Dress, pic=random.choice([ '露背装 (1).webp', '露背装 (2).webp', '露背装 (3).webp', '露背装 (4).webp', '露背装 (5).webp', '露背装 (6).webp', '露背装 (7).webp']), template = True, rank = 3, max_rank = 6, rarity = 3, price = 2400 , effects = (Effect('change', 'libido', 6), Effect('change', 'sensitivity', 6), Effect('change', 'obedience', 6), Effect('change', 'constitution', 12), ), description = "背后凉飕飕的，是不是有人在说坏话？"),
                            
                            Item(name = '低领上衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '低领上衣 (1).webp', '低领上衣 (2).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('boost', 'beauty gains', 0.08), ), description = "尽情地展示你的事业线吧~"),
                            Item(name = '高叉装®', target = 'girl', type = IT_Dress, pic=random.choice([ '高叉装 (1).webp', '高叉装 (2).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('boost', 'body gains', 0.08), ), description = "跳健美操时很方便活动，做其他事也很方便。"),
                            Item(name = '针织毛衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '针织毛衣 (1).webp', '针织毛衣 (2).webp', '针织毛衣 (3).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('boost', 'charm gains', 0.08), ), description = "劈里啪啦~这不是电魔法，这是静电。"),
                            Item(name = '超短裙®', target = 'girl', type = IT_Dress, pic=random.choice([ '超短裙 (1).webp', '超短裙 (2).webp', '超短裙 (3).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('boost', 'refinement gains', 0.08), ), description = "只要稍微弯一点腰，就能看到....答应我，别穿安全裤好吗？"),

                            Item(name = '吊带裙®', target = 'girl', type = IT_Dress, pic=random.choice([ '吊带裙 (1).webp', '吊带裙 (2).webp', '吊带裙 (3).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1000 , effects = (Effect('boost', 'libido gains', 0.08), ), description = "吊带裙适合老肩巨滑的女人。"),
                            Item(name = '高叉裙®', target = 'girl', type = IT_Dress, pic=random.choice([ '高叉裙 (1).webp', '高叉裙 (2).webp', '高叉裙 (3).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1000 , effects = (Effect('boost', 'obedience gains', 0.08), ), description = "可以方便的掀起前面和后面，我是说掀起来装东西。"),
                            Item(name = '浴衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '浴衣 (1).webp', '浴衣 (2).webp', '浴衣 (3).webp', '浴衣 (4).webp', '浴衣 (5).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1000 , effects = (Effect('boost', 'sensitivity gains', 0.08), ), description = "美人出浴，宽松的浴衣能给她最贴心的呵护。"),
                            Item(name = '牛仔裤®', target = 'girl', type = IT_Dress, pic=random.choice([ '牛仔裤 (1).webp', '牛仔裤 (2).webp', '牛仔裤 (3).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1000 , effects = (Effect('boost', 'constitution gains', 0.08), ), description = "结实耐磨的面料，也是让女人减肥的动力之一。"),
                            
                            Item(name = '啦啦队服®', target = 'girl', type = IT_Dress, pic=random.choice([ '啦啦队服 (1).webp', '啦啦队服 (2).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 450 , effects = (Effect('change', 'charm', 6), Effect('change', 'beauty', 6), ), description = "一二三，加油！能够唤起雄性的动力。"),
                            Item(name = '圣诞装®', target = 'girl', type = IT_Dress, pic=random.choice([ '圣诞装 (1).webp', '圣诞装 (2).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 450 , effects = (Effect('change', 'beauty', 6), Effect('change', 'body', 6), ), description = "圣诞节快乐！不听话的坏孩子可没有礼物哦~"),
                            Item(name = '兔女郎®', target = 'girl', type = IT_Dress, pic=random.choice([ '兔女郎 (1).webp', '兔女郎 (2).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 450 , effects = (Effect('change', 'body', 6), Effect('change', 'refinement', 6), ), description = "长耳朵，短尾巴，渔网袜。记得带上你的大萝卜，她最爱吃了。"),
                            Item(name = '巫女服®', target = 'girl', type = IT_Dress, pic=random.choice([ '巫女服 (1).webp', '巫女服 (2).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 450 , effects = (Effect('change', 'refinement', 6), Effect('change', 'charm', 6), ), description = "巫女祭祀时穿的衣服，祈福时漏的越多效果越好。"),
                            
                            Item(name = '旗袍®', target = 'girl', type = IT_Dress, pic=random.choice([ '旗袍.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 , effects = (Effect('change', 'libido', 5), Effect('change', 'body', 6), ), description = "东方传统服饰，尽享雍容华贵。"),
                            Item(name = '汉服®', target = 'girl', type = IT_Dress, pic=random.choice([ '汉服 (1).webp', '汉服 (2).webp', '汉服 (3).webp', '汉服 (4).webp', '汉服 (5).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 , effects = (Effect('change', 'charm', 6), Effect('change', 'sensitivity', 6), ), description = "如果你有耐心一层又一层地拨开洋葱，那这衣服一定适合你。"),
                            Item(name = '瑜伽服®', target = 'girl', type = IT_Dress, pic=random.choice([ '瑜伽服.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 , effects = (Effect('change', 'beauty', 6), Effect('change', 'obedience', 6), ), description = "拜拜甜甜圈，燃烧你的卡路里！"),
                            Item(name = '胶衣®', target = 'girl', type = IT_Dress, pic=random.choice([ '胶衣 (1).webp', '胶衣 (2).webp', '胶衣 (3).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 , effects = (Effect('change', 'refinement', 6), Effect('change', 'constitution', 6), ), description = "贴身的胶衣，搜查官的标配，谁知道里面有多闷。"),
                            
                            Item(name = '警察制服®', target = 'girl', type = IT_Dress, pic=random.choice([ '警察制服 (1).webp', '警察制服 (2).webp', '警察制服 (3).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 750 , effects = (Effect('change', 'beauty', 6), Effect('change', 'charm', 6), Effect('change', 'body', 6), Effect('change', 'refinement', -4), ), description = "不许动，举起手来！把你的武器...哦，你的武器看起来很危险。"),
                            Item(name = '空姐制服®', target = 'girl', type = IT_Dress, pic=random.choice([ '空姐制服 (1).webp', '空姐制服 (2).webp', '空姐制服 (3).webp', '空姐制服 (4).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 750 , effects = (Effect('change', 'beauty', 6), Effect('change', 'charm', 6), Effect('change', 'refinement', 6), Effect('change', 'body', -4), ), description = "欢迎乘坐泽恩航空，尊贵的VIP客户，请问需要特殊服务吗？"),
                            Item(name = '女仆装®', target = 'girl', type = IT_Dress, pic=random.choice([ '女仆装 (1).webp', '女仆装 (2).webp', '女仆装 (3).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 750 , effects = (Effect('change', 'beauty', -4), Effect('change', 'charm', 6), Effect('change', 'refinement', 6), Effect('change', 'body', 6), ), description = "这身衣服打扫卫生似乎并不方便，不过主人喜欢就够了。"),
                            Item(name = 'JK服®', target = 'girl', type = IT_Dress, pic=random.choice([ 'JK服 (1).webp', 'JK服 (2).webp', 'JK服 (3).webp', 'JK服 (4).webp', 'JK服 (5).webp', 'JK服 (6).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 750 , effects = (Effect('change', 'beauty', 6), Effect('change', 'charm', -4), Effect('change', 'refinement', 6), Effect('change', 'body', 6), ), description = "未成年的衣服还得是成年人穿起来才有那味~"),

                            Item(name = '舞女服®', target = 'girl', type = IT_Dress, pic=random.choice([ '舞女服 (1).webp', '舞女服 (2).webp', '舞女服 (3).webp', '舞女服 (4).webp', '舞女服 (5).webp', '舞女服 (6).webp', '舞女服 (7).webp', '舞女服 (8).webp', '舞女服 (9).webp', '舞女服 (10).webp', '舞女服 (11).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('change', 'libido', -4), Effect('change', 'sensitivity', 6), Effect('change', 'obedience', 6), Effect('change', 'constitution', 6), ), description = "翩若惊鸿，宛如游龙，伴随着音乐的节奏，身上的衣物越来越少。"),
                            Item(name = '泳装®', target = 'girl', type = IT_Dress, pic=random.choice([ '泳装 (1).webp', '泳装 (2).webp', '泳装 (3).webp', '泳装 (4).webp', '泳装 (5).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('change', 'libido', 6), Effect('change', 'sensitivity', -4), Effect('change', 'obedience', 6), Effect('change', 'constitution', 6), ), description = "竞技泳装，学校泳装，比基尼，总有一款适合你。"),
                            Item(name = '领带®', target = 'girl', type = IT_Dress, pic=random.choice([ '领带 (1).webp', '领带 (2).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('change', 'libido', 5), Effect('change', 'sensitivity', 6), Effect('change', 'obedience', 6), Effect('change', 'constitution', -4), ), description = "领带什么都挡不住，不过可以拽着当链子。"),
                            Item(name = '肚兜®', target = 'girl', type = IT_Dress, pic=random.choice([ '肚兜 (1).webp', '肚兜 (2).webp', '肚兜 (3).webp', '肚兜 (4).webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 , effects = (Effect('change', 'libido', 6), Effect('change', 'sensitivity', 6), Effect('change', 'obedience', -4), Effect('change', 'constitution', 6), ), description = "东方传统女性的贴身衣物，上面绣着小鸭子，啊不对，是鸳鸯。"),

                            ]


        # Generate variable quality items
        # all_items += generate_template_items(template_items)

        for it in template_items:
            for i in range(0,7):
                if it.min_rank <= i <= it.max_rank:
                    all_items.append(it.generate_new_item(i))

        item_dict = {it.name : it for it in all_items}

    return
